### ISSUE TITLE
Web pack 2

### ISSUE THREAD

**Issue by dcworldwide** [lobsteropteryx/esri-webpack-typescript#11]
Could you please upgrade to Web pack 2? Ir would be helpful to know if solution is future proof.

**Comment by tomwayson** [comment]
@dcworldwide the solution does appear to be future proof. @jwasilgeo has updated my babel fork of this repo to use webpack 2: https://github.com/tomwayson/esri-webpack-babel/pull/8

I don't see anything there that wouldn't be compatible w/ TypeScript. You should give those changes a spin, and if they work, PR back here.

**Comment by dcworldwide** [comment]
Will do thanks. I'm about to update a large esri js Webpack 1 project to 2 so happy to hear that.

**Comment by lobsteropteryx** [comment]
Hey all--I just saw this today, not sure what happened to the notifications!

I went ahead and pulled in @jwasilgeo 's updates for webpack 2.  I also did some minor cleanup--adding a postinstall for the typings, hot module reloading, and generating the index file.

**Comment by dcworldwide** [comment]
Sweet great work. Will be trying this out myself next week
