### ISSUE TITLE
Make it more obvious that this uses TypeScript

### ISSUE THREAD

**Issue by tomwayson** [lobsteropteryx/esri-webpack-typescript#6]
At the very least that should be mentioned in the README and repo description. I'd also suggest appending `-typescript` to the repo name.

If you agree and decide to change the repo name/description, let me know and I could make a PR w/ changes to the README and package.json.

**Comment by lobsteropteryx** [comment]
Totally agree.

**Comment by lobsteropteryx** [comment]
I changed the repo name, and updated the readme and package.json.  Feel free to submit a PR if you want to add more detail, but I'm going to close this for now.

**Comment by tomwayson** [comment]
Great! I only saw one other place to update it and made PR #8 

thanks!
