### ISSUE TITLE
update to ArcGIS API for JavaScript 3.17

### ISSUE THREAD

**Issue by tomwayson** [lobsteropteryx/esri-webpack-typescript#7]
I'd have PR'd this myself already but wasn't sure what the status of #1 is.

I suggest keeping the repo configured to the latest 3.x for now, but also including commented out lines that would show the corresponding config/code for 4.x.

If you agree, I can do that in a PR.

**Comment by lobsteropteryx** [comment]
That makes sense.  Either that, or separate branches for 3.x / 4.x ?

**Comment by tomwayson** [comment]
Separate branches is probably more useful but a bit more work to maintain. The API versions only get bumped a couple times a year tho, and as long as you don't plan to add a bunch of stuff to this repo that would need to be added twice, I'd say branches would work. I'll PR that.

**Comment by lobsteropteryx** [comment]
I updated master to 3.17.  Looking at the changes for 4.0, I think a branch is the best solution, since we won't be able to comment changes in the .json files.

I asked @dastevens to repoint his PR, and I'm going to close this issue.

Thanks!
